// src/app/share/[id]/page.tsx
"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Sparkles, Globe, AlertTriangle } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

export default function SharedChatView() {
  const { id } = useParams();
  const [chat, setChat] = useState<any>(null);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/share/${id}`)
      .then(res => res.json())
      .then(data => {
        if (data.error) setError(data.error);
        else setChat(data.chat);
      })
      .catch(() => setError("Failed to load chat"))
      .finally(() => setIsLoading(false));
  }, [id]);

  if (isLoading) {
    return <div className="min-h-screen bg-[#131314] flex items-center justify-center text-[#c4c7c5] animate-pulse">Loading Shared Chat...</div>;
  }

  if (error || !chat) {
    return (
      <div className="min-h-screen bg-[#131314] flex flex-col items-center justify-center text-[#e3e3e3]">
        <AlertTriangle size={48} className="text-[#ff5546] mb-4" />
        <h1 className="text-2xl font-medium mb-2">Chat Not Found</h1>
        <p className="text-[#c4c7c5]">This link is invalid or the creator has made it private.</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen w-full bg-[#131314] text-[#e3e3e3] overflow-y-auto font-sans selection:bg-[#a8c7fa]/30 selection:text-white custom-scrollbar">
      <header className="sticky top-0 w-full p-4 flex items-center justify-between z-10 bg-[#131314]/80 backdrop-blur-md border-b border-[#444746]/30">
        <h1 className="text-[20px] font-medium text-[#e3e3e3] opacity-80 flex items-center gap-2">
          <Sparkles size={20} className="text-[#a8c7fa]" /> Sweet AI (Shared)
        </h1>
        <div className="text-[14px] text-[#c4c7c5] font-medium truncate max-w-[150px] md:max-w-[400px]">
          {chat.title}
        </div>
      </header>

      <div className="max-w-[800px] mx-auto px-4 py-12 flex flex-col gap-8 md:gap-10 pb-32">
        {chat.messages.map((msg: any) => (
          <div key={msg.id} className={`flex gap-3 md:gap-5 w-full ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
            {msg.role === "ai" && (
              <div className="w-7 h-7 md:w-8 md:h-8 shrink-0 rounded-full flex items-center justify-center mt-1 bg-gradient-to-br from-[#4b90ff] to-[#ff5546]">
                <Sparkles size={14} className="text-white" />
              </div>
            )}

            <div className={`flex flex-col gap-1 ${msg.role === "user" ? "items-end max-w-[90%] md:max-w-[80%]" : "w-full items-start"}`}>
              <div className={`text-[15px] md:text-[16px] leading-relaxed md:leading-loose ${
                msg.role === "user" ? "bg-[#1e1f20] text-[#e3e3e3] px-5 py-3 md:px-6 rounded-[24px]" : "text-[#e3e3e3] w-full pt-1"
              }`}>
                {msg.role === "user" ? (
                  msg.text
                ) : (
                  <div className="prose prose-invert max-w-none prose-p:leading-loose prose-pre:bg-[#1e1f20] prose-pre:rounded-2xl prose-a:text-[#a8c7fa]">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.text}</ReactMarkdown>
                    {msg.sources && msg.sources.length > 0 && (
                      <div className="flex flex-wrap items-center gap-2 mt-4 pt-4 border-t border-[#444746]/50">
                        <span className="text-[12px] font-medium text-[#c4c7c5] flex items-center gap-1.5"><Globe size={14} /> Sources:</span>
                        {msg.sources.map((source: any, idx: number) => (
                          <a key={idx} href={source.url} target="_blank" rel="noreferrer" className="flex items-center gap-1.5 px-3 py-1.5 bg-[#282a2c] hover:bg-[#444746] rounded-full text-[12px] text-[#a8c7fa] border border-transparent hover:border-[#5f6368] transition-colors truncate max-w-[150px]">
                            {source.title}
                          </a>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="fixed bottom-6 left-0 right-0 flex justify-center pointer-events-none">
         <div className="bg-[#1e1f20]/90 backdrop-blur-md px-6 py-3 rounded-full border border-[#444746] text-[13px] text-[#c4c7c5] shadow-xl">
            This is a read-only chat generated by Sweet AI.
         </div>
      </div>
    </div>
  );
}
